services:
  # postgres:
  #   image: postgres:15.2-alpine
  #   environment:
  #     POSTGRES_USER: prefect
  #     POSTGRES_PASSWORD: prefect
  #     POSTGRES_DB: prefect
  #   volumes:
  #     - prefect-postgres-data:/var/lib/postgresql/data
  #   ports:
  #     - "5432:5432"
  #   healthcheck:
  #     test: ["CMD", "pg_isready", "-U", "prefect"]
  #     interval: 5s
  #     timeout: 5s
  #     retries: 5
  #   networks:
  #     - dev-network

  prefect:
    image: prefecthq/prefect:3-python3.11
    restart: always
    environment:
      - PREFECT_API_URL=http://localhost:4200/api
      - PREFECT_SERVER_API_HOST=0.0.0.0
      - PREFECT_SERVER_API_PORT=4200
    ports:
      - "4200:4200"
    command: ["prefect", "server", "start"]
    volumes:
      - prefect-data:/root/.prefect
    networks:
      - dev-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4200/api/health"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  development:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/app/src
      - ./scripts:/app/scripts
      - ./data:/app/data
    environment:
      - PREFECT_API_URL=http://prefect:4200/api
      - PREFECT_RESULTS_PERSIST_BY_DEFAULT=false
    # depends_on:
    #   prefect:
    #     condition: service_healthy
    networks:
      - dev-network

  # litellm-proxy:
  #   image: ghcr.io/berriai/litellm:main-latest
  #   container_name: litellm-proxy
  #   ports:
  #     - "127.0.0.1:4000:4000"
  #   volumes:
  #     - ./litellm_config.yaml:/app/config.yaml
  #     - litellm-logs:/var/log/litellm
  #   environment:
  #     - OPENROUTER_API_KEY=${OPENROUTER_API_KEY}
  #     - LITELLM_MASTER_KEY=${LITELLM_MASTER_KEY}
  #     - LITELLM_SALT_KEY=${LITELLM_SALT_KEY}
  #     - DATABASE_URL=${DATABASE_URL}
  #   command: >
  #     --config /app/config.yaml 
  #     --port 4000 
  #     --host 0.0.0.0 
  #     --num_workers 10
  #     --request_timeout 60
  #   healthcheck:
  #     test: ["CMD", "curl", "-f", "http://localhost:4000/health"]
  #     interval: 30s
  #     timeout: 10s
  #     retries: 3
  #     start_period: 20s
  #   restart: unless-stopped
  #   depends_on:
  #     postgres:
  #       condition: service_healthy
  #   networks:
  #     - dev-network

volumes:
  prefect-data:
  prefect-postgres-data:

networks:
  dev-network:
    name: prefect-dev-network
    external: false